// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmcapndeqbbqgnigipvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtY2FwbmRlcWJicWduaWdpcHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDEwMzIsImV4cCI6MjA2NTQ3NzAzMn0.P44Mt8up8-NRKiB4t3YyGDeFLKIw9qWutjRo-7zeWHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);